version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_demo_project
      POSTGRES_USER: aliasgarli
      POSTGRES_PASSWORD: 123456789
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - db_app_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aliasgarli -d db_demo_project" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: app
    environment:
      DB_HOST: db
    ports:
      - "8080:8080"
    networks:
      - db_app_network
    depends_on:
      db:
        condition: service_healthy
networks:
  db_app_network:
    driver: bridge
volumes:
  pg_data:

#
#
#
#services:
#  dba:
#    image: postgres:latest
#    container_name: db_demoproject_app
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: db_demo_project
#      POSTGRES_USER: aliasgarli
#      POSTGRES_PASSWORD: 123456789
#    volumes:
#      - ./pg_data:/var/lib/postgresql/data
#    networks:
#      - db_app_network
#    healthcheck:
#      test: ["CMD-SHELL","pg_isready -h db_demoproject_app -U aliasgarli -d db_demo_project"]
#      interval: 50s
#      timeout: 15s
#      retries: 5